steps:
    # Instalar dependencias
    - name: "gcr.io/cloud-builders/npm"
      args: ["install"]
    # Crear la build del proyecto React
    - name: "gcr.io/cloud-builders/npm"
      args: ["run", "build"]
    # Desplegar en un servidor estático en Google Cloud
    - name: "gcr.io/cloud-builders/gsutil"
      args: ["-m", "rsync", "-r", "-c", "-d", "./build", "gs://my-react-app"]
